force-app/main/default/objects/Dealer_Performance_Review__c/Dealer_Performance_Review__c.object-meta.xml
<CustomObject>
    <label>Dealer Performance Review</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Dealer Performance Review Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Performance Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_Performance_Review__c/fields/Dealer_Account__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Account__c</fullName>
    <label>Dealer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Performance Reviews</relationshipLabel>
    <relationshipName>Dealer_Performance_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dealer_Performance_Review__c/fields/Dealer_Business_Planning__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Business_Planning__c</fullName>
    <label>Dealer Business Planning</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Average</fullName>
            </value>
            <value>
                <fullName>Needs Improvement</fullName>
            </value>
            <value>
                <fullName>Low Quality</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dealer_Performance_Review__c/fields/Dealer_Implementation_Description__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Implementation_Description__c</fullName>
    <label>Dealer Implementation Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Dealer_Performance_Review__c/fields/Dealer_Quality__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Quality__c</fullName>
    <label>Dealer Quality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dealer_Performance_Review__c/fields/Overall_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Overall_Feedback__c</fullName>
    <label>Overall Feedback</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Dealer_Performance_Review__c/fields/Overall_Rating__c.field-meta.xml
<CustomField>
    <fullName>Overall_Rating__c</fullName>
    <label>Overall Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DealerReviewController.cls
public with sharing class DealerReviewController {
    @AuraEnabled (cacheable=true)
    public static list<Dealer_Performance_Review__c> getDealerReview(String dealerAccountId){
        try {
            return [SELECT Id, Name, CreatedById,CreatedBy.Name,CreatedBy.email,Overall_Feedback__c, Overall_Rating__c, Dealer_Account__c, Dealer_Account__r.Name,Dealer_Business_Planning__c, Dealer_Implementation_Description__c,Dealer_Quality__c FROM Dealer_Performance_Review__c where Dealer_Account__c =: dealerAccountId];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    } 
}