force-app/main/default/objects/Account/fields/Dealer_Active_Pipeline_Value__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Active_Pipeline_Value__c</fullName>
    <label>Dealer Active Pipeline Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_Budget__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Budget__c</fullName>
    <label>Dealer Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_Contarct_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Contarct_End_Date__c</fullName>
    <label>Dealer Contarct End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_Contarct_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Contarct_Start_Date__c</fullName>
    <label>Dealer Contarct Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_Geolocation__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Geolocation__c</fullName>
    <label>Dealer Geolocation</label>
    <scale>6</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_Primary_POC__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Primary_POC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer Primary POC</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_Status__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Status__c</fullName>
    <label>Dealer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_Total_Sales_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Total_Sales_Revenue__c</fullName>
    <label>Dealer Total Sales Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_Training_Completed__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Training_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dealer Training Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_Website__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Website__c</fullName>
    <label>Dealer Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Trend_Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Trend_Partner_Contact__c</fullName>
    <label>Number of Trend Partner Contact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DealerSearchResultController.cls
public with sharing class DealerSearchResultController {
   
        @AuraEnabled(cacheable=true)
        public static list<account> getDealers(String dealerStateId ){
    
            if(String.isEmpty(dealerStateId)){
                system.debug('emptydealerStateId');
                return [SELECT Id, Name, Dealer_State__c, Dealer_State__r.Name, Dealer_Budget__c, Dealer_Total_Sales_Revenue__c, Dealer_Active_Pipeline_Value__c,
                Dealer_Primary_POC__c, Dealer_Primary_POC__r.Name,Dealer_Primary_POC__r.title, Dealer_Primary_POC__r.Salutation, Dealer_Contarct_Start_Date__c, Dealer_Contarct_End_Date__c, Dealer_Training_Completed__c, 
                Dealer_Status__c, Number_of_trend_Partner_contact__c, Dealer_WebSite__c, Dealer_Geolocation__Latitude__s, 
                Dealer_Geolocation__Longitude__s, Dealer_Geolocation__c,(Select FirstName,LastName,title,Salutation from Contacts) FROM Account WHERE Dealer_Status__c IN ('Active','Inactive','Pending')];
            } else{
                system.debug('dealerStateId'+dealerStateId);
                return [SELECT Id, Name, Dealer_State__c, Dealer_State__r.Name, Dealer_Budget__c, Dealer_Total_Sales_Revenue__c, Dealer_Active_Pipeline_Value__c,
            Dealer_Primary_POC__c, Dealer_Primary_POC__r.Name,Dealer_Primary_POC__r.title, Dealer_Primary_POC__r.Salutation, Dealer_Contarct_Start_Date__c, Dealer_Contarct_End_Date__c, Dealer_Training_Completed__c, 
            Dealer_Status__c, Number_of_trend_Partner_contact__c, Dealer_WebSite__c, Dealer_Geolocation__Latitude__s, 
            Dealer_Geolocation__Longitude__s, Dealer_Geolocation__c,(Select FirstName,LastName,title,Salutation from Contacts) FROM Account WHERE Dealer_Status__c IN ('Active','Inactive','Pending') AND Dealer_State__c =: dealerStateId];
            }
            
        }
    }